algoritmo "semnome"
// Função :
// Autor :
// Data : 13/08/2022
// Seção de Declarações 
var
num1,num2:inteiro
inicio
// Seção de Comandos
escreva("Informe o primeiro numero")
leia(num1)
escreva("Informe o segundo numero")
leia(num2)
se (num1 < num2) entao
   escreva("o numero",num1, "é menor")
senao
  se (num1 > num2) entao
     escreva("o numero",num2,"é maior")
  senao
     escreva("os numeros",num1, " e",num2, " sao iguais")
  fimse
fimse
fimalgoritmo
